version: '3'
services:
  web:
    image: nginx
    networks:
      - frontnet
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - backnet
networks:
  frontnet:
  backnet: